import type { Metadata } from "next";
import { Geist, Geist_Mono, Catamaran } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const catamaran = Catamaran({
  variable: "--font-catamaran", // Define a CSS variable for Catamaran
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${catamaran.variable} antialiased mx-[100px]`}
      >
        {children}
      </body>
    </html>
  );
}
